### ISSUE TITLE
运行故障

### ISSUE THREAD

**Issue by panhozet** [IKeepMoving/xuexiqiangguo#6]
没有运行成功 帮我看看啦 

我按照要求尝试配置了环境但没能正确运行 cmd中的错误如下
Python版本是3.8.2 使用USB连接
我没有代码经验 除了 uiautomator numpy 没有安装过其他依赖库

`
F:\adb\xuexiqiangguo-master>python study.py
Unknown input method com.android.adbkeyboard/.AdbIME cannot be selected for user #0
Traceback (most recent call last):
  File "C:\Users\pyl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\uiautomator\__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "C:\Users\pyl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\uiautomator\__init__.py", line 133, in __call__
    raise JsonRPCError(
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=北京]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "study.py", line 145, in <module>
    watch_local()
  File "study.py", line 83, in watch_local
    driver(text='北京').click()
  File "C:\Users\pyl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\uiautomator\__init__.py", line 76, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\pyl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\uiautomator\__init__.py", line 971, in _click
    return self.jsonrpc.click(self.selector)
  File "C:\Users\pyl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\uiautomator\__init__.py", line 458, in wrapper
    return _method_obj(*args, **kwargs)
  File "C:\Users\pyl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\uiautomator\__init__.py", line 133, in __call__
    raise JsonRPCError(
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=北京]

F:\adb\xuexiqiangguo-master>`

**Comment by IKeepMoving** [comment]
你安装了那个adb中文输入需要的环境了吗

**Comment by pigzcm** [comment]
Input method com.android.adbkeyboard/.AdbIME selected
Traceback (most recent call last):
  File "C:\Users\zcm19\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\uiautomator\__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "C:\Users\zcm19\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\uiautomator\__init__.py", line 133, in __call__
    raise JsonRPCError(
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=北京]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\study.py", line 145, in <module>
    watch_local()
  File ".\study.py", line 83, in watch_local
    driver(text='北京').click()
  File "C:\Users\zcm19\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\uiautomator\__init__.py", line 76, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\zcm19\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\uiautomator\__init__.py", line 971, in _click
    return self.jsonrpc.click(self.selector)
  File "C:\Users\zcm19\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\uiautomator\__init__.py", line 458, in wrapper
    return _method_obj(*args, **kwargs)
  File "C:\Users\zcm19\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\uiautomator\__init__.py", line 133, in __call__
    raise JsonRPCError(
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=北京]
